#!/bin/bash

set -euo pipefail

tag_file="release-in-progress"

create_commit() {
    sed -i -E "s/^version=.+$/version=$1/" gradle.properties
    git add gradle.properties
    git commit -q -m "$2"
}

prepare() {
    local version="$(sed -n -E 's/^version=(.+)$/\1/p' gradle.properties)"
    local v=( ${version//./ } )
    local release_version="${v[0]}.${v[1]}.${v[2]}.touch"
    local snapshot_version="${v[0]}.${v[1]}.$(( ${v[2]} + 1 )).touch-SNAPSHOT"
    local tag="v$release_version"

    create_commit "$release_version" "Release v$release_version"
    git tag "$tag"
    create_commit "$snapshot_version" "Next development version (v$snapshot_version)"
    echo "$tag" > "$tag_file"

    echo "Done!"
}

deploy() {
    local tag="$(cat "$tag_file")"

    git checkout "$tag"
    ./gradlew clean
    ./gradlew publishMavenJavaPublicationToMavenRepository
    rm "$tag_file"

    echo
    echo "Done!"
}

case "${1:-}" in
    prepare)
        prepare
        ;;
    deploy)
        deploy
        ;;
    *)
        echo "usage: ./release [prepare|deploy]"
        exit 1
        ;;
esac
